name: stranded
version: 0.0.1
description: A simple console application.
dependencies:
  collection: any
  meta: any
  built_value: any
  quiver: any

dev_dependencies:
  build: any
  built_value_generator: any
  source_gen: any
  test: any